version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/caspar-sup
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: docker build -t nfpis/caspar-sup:build_${CIRCLE_BUILD_NUM} -t nfpis/caspar-sup:${CIRCLE_SHA1} -t nfpis/caspar-sup:latest .
      - run:
          name: Run test and lint
          command: |
            docker run nfpis/recording_control npm run lint
            docker run nfpis/recording_control npm run test
      - deploy:
          name: Push to docker
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push nfpis/caspar-sup
workflows:
  version: 2
  build_deploy:
    jobs:
      - build:
          context: org-global
